version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: devops_hotels_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: devops123

  user-service:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/devops_hotels_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: devops123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"
    depends_on:
      - postgres-db
    restart: on-failure

volumes:
  postgres-db:
